In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
array_3d = np.arange(0,27).reshape(3,3,3)
array_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
array_3d * 2

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]],

       [[36, 38, 40],
        [42, 44, 46],
        [48, 50, 52]]])

In [14]:
one_array = np.ones((3,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
mult = np.arange(1,4)
mult

array([1, 2, 3])

In [17]:
one_array * mult

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [18]:
np.sqrt(array_3d)

array([[[0.        , 1.        , 1.41421356],
        [1.73205081, 2.        , 2.23606798],
        [2.44948974, 2.64575131, 2.82842712]],

       [[3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739],
        [3.87298335, 4.        , 4.12310563]],

       [[4.24264069, 4.35889894, 4.47213595],
        [4.58257569, 4.69041576, 4.79583152],
        [4.89897949, 5.        , 5.09901951]]])

In [19]:
np.exp(array_3d)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
        [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]],

       [[8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
        [3.26901737e+06, 8.88611052e+06, 2.41549528e+07]],

       [[6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
        [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
        [2.64891221e+10, 7.20048993e+10, 1.95729609e+11]]])

In [20]:
np.sin(array_3d)

array([[[ 0.        ,  0.84147098,  0.90929743],
        [ 0.14112001, -0.7568025 , -0.95892427],
        [-0.2794155 ,  0.6569866 ,  0.98935825]],

       [[ 0.41211849, -0.54402111, -0.99999021],
        [-0.53657292,  0.42016704,  0.99060736],
        [ 0.65028784, -0.28790332, -0.96139749]],

       [[-0.75098725,  0.14987721,  0.91294525],
        [ 0.83665564, -0.00885131, -0.8462204 ],
        [-0.90557836, -0.13235175,  0.76255845]]])

In [21]:
np.cos(array_3d)

array([[[ 1.        ,  0.54030231, -0.41614684],
        [-0.9899925 , -0.65364362,  0.28366219],
        [ 0.96017029,  0.75390225, -0.14550003]],

       [[-0.91113026, -0.83907153,  0.0044257 ],
        [ 0.84385396,  0.90744678,  0.13673722],
        [-0.75968791, -0.95765948, -0.27516334]],

       [[ 0.66031671,  0.98870462,  0.40808206],
        [-0.54772926, -0.99996083, -0.53283302],
        [ 0.42417901,  0.99120281,  0.64691932]]])

In [22]:
np.log(array_3d)

<ipython-input-22-b4fc381d176f>:1: RuntimeWarning: divide by zero encountered in log
  np.log(array_3d)


array([[[      -inf, 0.        , 0.69314718],
        [1.09861229, 1.38629436, 1.60943791],
        [1.79175947, 1.94591015, 2.07944154]],

       [[2.19722458, 2.30258509, 2.39789527],
        [2.48490665, 2.56494936, 2.63905733],
        [2.7080502 , 2.77258872, 2.83321334]],

       [[2.89037176, 2.94443898, 2.99573227],
        [3.04452244, 3.09104245, 3.13549422],
        [3.17805383, 3.21887582, 3.25809654]]])

In [23]:
np.tan(array_3d)

array([[[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00],
        [-1.42546543e-01,  1.15782128e+00, -3.38051501e+00],
        [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00]],

       [[-4.52315659e-01,  6.48360827e-01, -2.25950846e+02],
        [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00],
        [-8.55993401e-01,  3.00632242e-01,  3.49391565e+00]],

       [[-1.13731371e+00,  1.51589471e-01,  2.23716094e+00],
        [-1.52749853e+00,  8.85165604e-03,  1.58815308e+00],
        [-2.13489670e+00, -1.33526407e-01,  1.17875355e+00]]])

In [25]:
np.insert(arr,4,999)

array([  0,   1,   2,   3, 999,   4,   5,   6,   7,   8,   9,  10])

In [26]:
np.delete(arr,4)

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10])

In [27]:
np.append(arr,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((a,b),axis = None)

array([1, 2, 3, 4, 5, 6])

In [32]:
np.where(arr>5,1,arr)

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1, 1])

In [33]:
np.where(arr%2==0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even'], dtype='<U4')